// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: user_input.proto

package servicecalculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_input_proto_rawDescGZIP(), []int{0}
}

type GetUserBMIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBMIRequest) Reset() {
	*x = GetUserBMIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_input_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBMIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBMIRequest) ProtoMessage() {}

func (x *GetUserBMIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_input_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBMIRequest.ProtoReflect.Descriptor instead.
func (*GetUserBMIRequest) Descriptor() ([]byte, []int) {
	return file_user_input_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBMIRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserBMRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBMRRequest) Reset() {
	*x = GetUserBMRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_input_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBMRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBMRRequest) ProtoMessage() {}

func (x *GetUserBMRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_input_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBMRRequest.ProtoReflect.Descriptor instead.
func (*GetUserBMRRequest) Descriptor() ([]byte, []int) {
	return file_user_input_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBMRRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BMIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bmi float64 `protobuf:"fixed64,2,opt,name=bmi,proto3" json:"bmi,omitempty"`
}

func (x *BMIResponse) Reset() {
	*x = BMIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_input_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BMIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMIResponse) ProtoMessage() {}

func (x *BMIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_input_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMIResponse.ProtoReflect.Descriptor instead.
func (*BMIResponse) Descriptor() ([]byte, []int) {
	return file_user_input_proto_rawDescGZIP(), []int{3}
}

func (x *BMIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BMIResponse) GetBmi() float64 {
	if x != nil {
		return x.Bmi
	}
	return 0
}

type BMRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bmr float64 `protobuf:"fixed64,2,opt,name=bmr,proto3" json:"bmr,omitempty"`
}

func (x *BMRResponse) Reset() {
	*x = BMRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_input_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BMRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMRResponse) ProtoMessage() {}

func (x *BMRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_input_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMRResponse.ProtoReflect.Descriptor instead.
func (*BMRResponse) Descriptor() ([]byte, []int) {
	return file_user_input_proto_rawDescGZIP(), []int{4}
}

func (x *BMRResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BMRResponse) GetBmr() float64 {
	if x != nil {
		return x.Bmr
	}
	return 0
}

var File_user_input_proto protoreflect.FileDescriptor

var file_user_input_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x4d, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x4d, 0x52, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x0b, 0x42, 0x4d, 0x49, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x6d, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x62, 0x6d, 0x69, 0x22, 0x2f, 0x0a, 0x0b, 0x42, 0x4d, 0x52, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x6d, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x6d, 0x72, 0x32, 0xa2, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x49, 0x0a, 0x03, 0x42, 0x4d, 0x49, 0x12, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x4d, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x42, 0x4d, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x49, 0x0a, 0x03, 0x42, 0x4d, 0x52, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x4d, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x42, 0x4d, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6f, 0x6b,
	0x72, 0x6f, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_input_proto_rawDescOnce sync.Once
	file_user_input_proto_rawDescData = file_user_input_proto_rawDesc
)

func file_user_input_proto_rawDescGZIP() []byte {
	file_user_input_proto_rawDescOnce.Do(func() {
		file_user_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_input_proto_rawDescData)
	})
	return file_user_input_proto_rawDescData
}

var file_user_input_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_input_proto_goTypes = []interface{}{
	(*Empty)(nil),             // 0: protocalculator.Empty
	(*GetUserBMIRequest)(nil), // 1: protocalculator.GetUserBMIRequest
	(*GetUserBMRRequest)(nil), // 2: protocalculator.GetUserBMRRequest
	(*BMIResponse)(nil),       // 3: protocalculator.BMIResponse
	(*BMRResponse)(nil),       // 4: protocalculator.BMRResponse
}
var file_user_input_proto_depIdxs = []int32{
	1, // 0: protocalculator.Calculator.BMI:input_type -> protocalculator.GetUserBMIRequest
	2, // 1: protocalculator.Calculator.BMR:input_type -> protocalculator.GetUserBMRRequest
	3, // 2: protocalculator.Calculator.BMI:output_type -> protocalculator.BMIResponse
	4, // 3: protocalculator.Calculator.BMR:output_type -> protocalculator.BMRResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_input_proto_init() }
func file_user_input_proto_init() {
	if File_user_input_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_input_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBMIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_input_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBMRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_input_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BMIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_input_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BMRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_input_proto_goTypes,
		DependencyIndexes: file_user_input_proto_depIdxs,
		MessageInfos:      file_user_input_proto_msgTypes,
	}.Build()
	File_user_input_proto = out.File
	file_user_input_proto_rawDesc = nil
	file_user_input_proto_goTypes = nil
	file_user_input_proto_depIdxs = nil
}
