env: local

server:
  rest-port: 8081
  grpc-port: 50051

database_home:
  host: 192.168.1.187
  port: 5432
  name: mookrob
  user: meendev
  password: meenmook

database:
  host: localhost
  port: 5432
  name: mookrob
  user: meendev
  password: meenmook

client:
  meal-grpc-host: "localhost:50052"

rabbitmq:
  host:
  port:
  user:
  password:
