env: local

server:
  rest-port: 8081
  grpc-port: 50051

database:
  host: localhost
  port: 5440
  name: user
  user: postgres
  password: postgres

client:
  meal-grpc-host: "localhost:50052"
  auth-grpc-host: "localhost:50053"

jwt:
  secret_key: fsdfk&wq#452!dsd