env: local

server:
  port: 8083

database:
  host: localhost
  port: 5442
  name: authentication
  user: postgres
  password: postgres

jwt:
  secret_key: fsdfk&wq#452!dsd
  refresh_key: 4f#38i&$ah1l8&k4
