version: '3'

services:
  meal-app:
    environment:
      ENV: "dev"
      GIN_MODE: "release"
      REST_PORT: "8080"
      GRPC_PORT: "50050"
      DB_HOST: "192.168.1.39"
      DB_PORT: "5441"
      DB_NAME: "meal"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      JWT_SECRET_KEY: "m345lko@okr&0b"
    build:
      context: ..
      args:
        - DB_HOST=192.168.1.39
        - DB_PORT=5441
        - DB_NAME=meal
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
      dockerfile: /meal-service/Dockerfile
    ports:
      - "8082:8080"
      - "50052:50050"
