// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.3
// source: meal.proto

package servicemeal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{0}
}

type GetUserFavMealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserFavMealRequest) Reset() {
	*x = GetUserFavMealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFavMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFavMealRequest) ProtoMessage() {}

func (x *GetUserFavMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFavMealRequest.ProtoReflect.Descriptor instead.
func (*GetUserFavMealRequest) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserFavMealRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MealItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Energy       float64 `protobuf:"fixed64,3,opt,name=energy,proto3" json:"energy,omitempty"`
	Protein      float64 `protobuf:"fixed64,4,opt,name=protein,proto3" json:"protein,omitempty"`
	Carbohydrate float64 `protobuf:"fixed64,5,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`
	Fat          float64 `protobuf:"fixed64,6,opt,name=fat,proto3" json:"fat,omitempty"`
	Sodium       float64 `protobuf:"fixed64,7,opt,name=sodium,proto3" json:"sodium,omitempty"`
	Cholesterol  float64 `protobuf:"fixed64,8,opt,name=cholesterol,proto3" json:"cholesterol,omitempty"`
}

func (x *MealItem) Reset() {
	*x = MealItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealItem) ProtoMessage() {}

func (x *MealItem) ProtoReflect() protoreflect.Message {
	mi := &file_meal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealItem.ProtoReflect.Descriptor instead.
func (*MealItem) Descriptor() ([]byte, []int) {
	return file_meal_proto_rawDescGZIP(), []int{2}
}

func (x *MealItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MealItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealItem) GetEnergy() float64 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *MealItem) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *MealItem) GetCarbohydrate() float64 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *MealItem) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *MealItem) GetSodium() float64 {
	if x != nil {
		return x.Sodium
	}
	return 0
}

func (x *MealItem) GetCholesterol() float64 {
	if x != nil {
		return x.Cholesterol
	}
	return 0
}

var File_meal_proto protoreflect.FileDescriptor

var file_meal_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6d, 0x65, 0x61, 0x6c, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x4d, 0x65,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x08, 0x4d, 0x65,
	0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x66,
	0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x73, 0x6f, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68,
	0x6f, 0x6c, 0x65, 0x73, 0x74, 0x65, 0x72, 0x6f, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x63, 0x68, 0x6f, 0x6c, 0x65, 0x73, 0x74, 0x65, 0x72, 0x6f, 0x6c, 0x32, 0x53, 0x0a, 0x04,
	0x4d, 0x65, 0x61, 0x6c, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x61, 0x76, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x65,
	0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x4d, 0x65, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6d, 0x65, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x6f, 0x6f, 0x6b, 0x72, 0x6f, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x6d,
	0x65, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meal_proto_rawDescOnce sync.Once
	file_meal_proto_rawDescData = file_meal_proto_rawDesc
)

func file_meal_proto_rawDescGZIP() []byte {
	file_meal_proto_rawDescOnce.Do(func() {
		file_meal_proto_rawDescData = protoimpl.X.CompressGZIP(file_meal_proto_rawDescData)
	})
	return file_meal_proto_rawDescData
}

var file_meal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meal_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: protomeal.Empty
	(*GetUserFavMealRequest)(nil), // 1: protomeal.GetUserFavMealRequest
	(*MealItem)(nil),              // 2: protomeal.MealItem
}
var file_meal_proto_depIdxs = []int32{
	1, // 0: protomeal.Meal.GetUserFavMeal:input_type -> protomeal.GetUserFavMealRequest
	2, // 1: protomeal.Meal.GetUserFavMeal:output_type -> protomeal.MealItem
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meal_proto_init() }
func file_meal_proto_init() {
	if File_meal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFavMealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MealItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meal_proto_goTypes,
		DependencyIndexes: file_meal_proto_depIdxs,
		MessageInfos:      file_meal_proto_msgTypes,
	}.Build()
	File_meal_proto = out.File
	file_meal_proto_rawDesc = nil
	file_meal_proto_goTypes = nil
	file_meal_proto_depIdxs = nil
}
