apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: meal-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meal-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

