apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meal-app
  template:
    metadata:
      labels:
        app: meal-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mookrob-meal.cwle0giyacpw.us-east-1.rds.amazonaws.com
            - name: DB_NAME
              value: meal
            - name: DB_PASSWORD
              value: mookrob_password
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: mookrob
            - name: ENV
              value: dev
            - name: GIN_MODE
              value: release
            - name: GRPC_PORT
              value: "50050"
            - name: JWT_SECRET_KEY
              value: m345lko@okr&0b
            - name: REST_PORT
              value: "8080"
          image: 842358650856.dkr.ecr.us-east-1.amazonaws.com/mookrob-meal-app:latest
          name: meal-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50050
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
