env: local

server:
  rest-port: 8082
  grpc-port: 50052

database_home:
  host: 192.168.1.196
  port: 5432
  name: mookrob
  user: meendev
  password: meenmook

database:
<<<<<<< Updated upstream
  host: localhost
  port: 5432
  name: mookrob
  user: meendev
  password: meenmook

rabbitmq:
  host: 192.168.1.187
  port: 5672
  user: meendev
  password: meen
=======
  host: 192.168.1.184
  port: 5432
  name: joyjoydevelopment
  user: postgres
  password: meen
>>>>>>> Stashed changes
